# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dee59e6f43ba234e0475fbd4d61da964"
name = "live-cart-1"
application_url = "https://104a-2409-40c1-8-23e7-89b3-23f7-4132-9405.ngrok-free.app/api"
embedded = true

[webhooks]
api_version = "2026-04"
# carts/create and carts/update are subscribed programmatically on OAuth (WEBHOOK_ARR) to
# POST ${HOST}/webhook/carts_create and carts_update. To manage them in this file instead,
# see https://shopify.dev/docs/api/webhooks/latest?reference=toml

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,write_content,write_files,write_products,read_products,read_orders,read_themes,unauthenticated_read_customers,unauthenticated_read_content,unauthenticated_read_product_listings,unauthenticated_read_checkouts,unauthenticated_write_checkouts"
use_legacy_install_flow=true


[auth]
redirect_urls = [
  "https://104a-2409-40c1-8-23e7-89b3-23f7-4132-9405.ngrok-free.app/api",
  "https://104a-2409-40c1-8-23e7-89b3-23f7-4132-9405.ngrok-free.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
