const config = {
    "MODE":process.env.SERVER,
    "HOST":process.env.HOST,
    "secret": process.env.secret,
    "MONGODB_URL":process.env.MONGODB_URL,
    "MONGODB_NAME":process.env.MONGODB_NAME,
    'status_code_config': {
        'OK': 200,
        'CREATED': 201,
        'ACCEPTED': 202,
        'BAD_REQUEST': 400,
        'UNAUTHORIZED': 401,
        'PAYMENT_REQUIRED': 402,
        'FORBIDDEN': 403,
        'NOT_FOUND': 404,
        'UNPROCEESSABLE_ENTITY': 422,
        'INTERNAL_SERVER_ERROR': 500,
        'BAD_GATEWAY': 502
    },
    en_message_config: {
        'ERROR_NO_DATA_FOUND': 'No data found',
        'ERROR_SOMETHING_WRONG': 'Something went wrong!',
        'IMAGE_NOT_UPLOAD': 'Image Not upload!',
        'ERROR_NOT_VALID_TOKEN': 'Not valid token data.',
        'ERROR_TOKEN_NOT_FOUND': 'token not found.',
        'SHOP_NOT_FOUND' : 'SHOP not found',
        'SUCCESS_TOKEN_GENERATE' : "success token generate.",
        'MEMBER_NOT_REGISTERED': 'Member not registered!',
        'APP_UNISTALLED_WEBHOOK_SUCCESS' : 'successfully run app_unistalled webhook',
        'SHOP_UPDATE_WEBHOOK_SUCCESS' : 'successfully run shop_update webhook',
        'CARTS_WEBHOOK_SUCCESS' : 'successfully processed cart webhook',
        'ORDER_CART_WEBHOOK_SUCCESS' : 'successfully processed order/draft cart link webhook',
        'CUSTOMER_CREATE_WEBHOOK_SUCCESS' : 'successfully run app_unistalled webhook',
        'WEBHOOK_SUCCESS' : 'webhook run successfully',
        'TEST_FUNCTION_WORKING' : 'Test function working.',
        'RULE_ADD_SUCCESSFULLY' : 'Rule add successfully.',
        'RULE_FETCH_SUCCESSFULLY' : 'Rule get successfully.',
        'RULE_UPDATE_SUCCESSFULLY' : 'Rule update successfully.',
        'SUCCESS_ORDER_FROM_WOOCOMMERCE' : 'successfully get order from woocommerce.',
        'MOBILE_NOT_FOUND' : 'Mobile number not found.',
        'ACCOUNT_ALREADY_EXISTS' : 'Your account already exists.',
        'OTP_SEND_SUCCESSFULLY' : 'otp send successfully.',
        'OTP_NOT_FOUND' : 'otp not found.',
        'OTP_VERIFY_SUCCESSFULLY' : 'otp verify successfully.',
        'OTP_NOT_VERIFY_SUCCESSFULLY' : 'otp not verify successfully.',
        'CUSTOMER_DELETE_WEBHOOK_SUCCESS' : 'successfully run customer_delete webhook',
        'DATA_SAVED_SUCCESSFULLY' : 'data saved successfully.',
        'EMAIL_EXISTS': 'email exits!',
        'DATA_FETCH_SUCCESSFULLY' : 'data fetch successfully.',
        'ONBOARDING_FLOW_SUCCESSFULLY' : 'onboarding flow successfully.',
        'PHONE_ALREDY_USE_OR_SOMETHING_WENT_WRONG' : 'This phone number is already in use or something went wrong.'
    },
    SHOPIFY_API_KEY:process.env.SHOPIFY_API_KEY,
    SHOPIFY_SECRETE_API_KEY:process.env.SHOPIFY_API_SECRET,
    SHOPIFY_SHOP:process.env.SHOPIFY_SHOP,
    editor_url:process.env.EDITOR_URL,
    API_VERSION: "/api/2025-01",
    SHOPIFY_API_VERSION:"/admin/api/2025-10",
    ACTION_ENCRYPT: "encrypt",
    ACTION_DECRYPT: "decrypt",
    WEBHOOK_ARR: [
        'APP_UNINSTALLED',
        'SHOP_UPDATE',
        'APP_SUBSCRIPTIONS_UPDATE',
        'CARTS_CREATE',
        'CARTS_UPDATE',
        'ORDERS_CREATE',
        'DRAFT_ORDERS_CREATE',
    ],
    APP_PREFIX:process.env.SITE_PREFIX,
    APP_WEBHOOK_PREFIX:process.env.SITE_WEBHOOK_PREFIX,
    AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
    AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
    AWS_BUCKET_NAME: process.env.AWS_BUCKET_NAME,
    AWS_BUCKET_REGION: process.env.AWS_BUCKET_REGION,
    AWS_END_POINT: process.env.AWS_END_POINT,
    EXTENSION_BLOCK_KEY: process.env.EXTENSION_BLOCK_KEY,
    EXTENSION_BLOCK_NAME :process.env.EXTENSION_BLOCK_NAME,
    EXTENSION_UUID : process.env.EXTENSION_UUID,
    CART_TRANSFORM_ID : process.env.CART_TRANSFORM_ID,
    BASE64_CHARS : process.env.BASE64_CHARS

}

export default config;
